### ISSUE TITLE
IBAMR compilation error due to '-fgnu89-inline'

### ISSUE THREAD

**Issue by Raamkrishnan** [IBAMR/IBAMR#1485] opened 2022-08-22 21:17 UTC
Hi,

I am compiling IBAMR with Cmake. While compiling, I get the error:

gmake[2]: *** [ibtk/src/CMakeFiles/IBTK3d.dir/build.make:469: ibtk/src/CMakeFiles/IBTK3d.dir/boundary/cf_interface/CartCellDoubleLinearCFInterpolation.cpp.o] Error 1
error: invalid argument '-fgnu89-inline' not allowed with 'C++'

I am using macOS Monterey (Clang version - 13.1.6), GNU Fortran 11.2.0, CMake - 3.21.4. Can anyone tell me how to get rid of this error?

**Comment by Raamkrishnan** [comment] 2022-08-22 21:20
[CMakeError.log](https://github.com/IBAMR/IBAMR/files/9397654/CMakeError.log)
[CMakeOutput.log](https://github.com/IBAMR/IBAMR/files/9397655/CMakeOutput.log)
Attached are the CMakeError.log and CMakeOutput.log files.

**Comment by drwells** [comment] 2022-08-23 12:54
It looks like the C++ compiler somehow got a C flag. Could you also attach CMakeCache.txt from the build directory here?

**Comment by Raamkrishnan** [comment] 2022-08-23 18:23
Attached is the CMakeCache.txt.
[CMakeCache.txt](https://github.com/IBAMR/IBAMR/files/9409637/CMakeCache.txt)

**Comment by drwells** [comment] 2022-08-23 19:33
This might be the same as https://gitlab.kitware.com/cmake/cmake/-/issues/23805 - i.e., its a CMake bug caused by an unusual combination of features.

1. Can you use an older copy of CMake? 3.15 should be fine.
2. Which version of MPI are you using?

**Comment by Raamkrishnan** [comment] 2022-08-23 19:45
I use MPICH 3.4.2. I can try with an older version of CMake. Thank you for your suggestions.

**Comment by drwells** [comment] 2022-08-23 19:47
We might be able to put together a workaround for this though ultimately its really an upstream problem. Thanks for the report either way!

**Comment by drwells** [comment] 2023-05-06 18:58
To the best of my knowledge this was fixed by https://github.com/Homebrew/homebrew-core/pull/94029 - there's not a lot I can do about bugs in homebrew and since this is fixed upstream I'm going to close this issue.

**Closed by drwells** 2023-05-06 18:58 UTC
Labels: Build System
